// System wrapper used by Marlin and generic integration checks.
//
// cpu_enable_i selects the command producer: the host's standalone OBJEKT port
// or the autonomous LOGIK processor. The response follows the same ownership.
// Change ownership only with LOGIK halted or at a service break and OBJEKT idle.
// The Rust harness enforces that rule before host commands or collection.
//
// The command/response enable inputs inject backpressure in protocol tests.
// Tie both high in a system that does not need this test facility. Memory and
// backing-store channels remain independent and can stall in either mode.
// Capacities: 16 pager slots, 512 object-memory words, 8192 microinstructions,
// 256 NAM words, 1024 opcode-map entries, and 32 words in each resident stack.
`ifndef REKURSIV_SIM_MEMORY_WORDS
`define REKURSIV_SIM_MEMORY_WORDS 512
`endif
module objekt_tb(
    input wire clk_i, input wire rst_i, input wire run_i,
    input wire cmd_valid_i, output wire cmd_ready_o,
    input wire [3:0] pager_i, input wire [3:0] index_i,
    input wire [2:0] register_i, input wire [1:0] memory_i,
    input wire [3:0] read_i, input wire load_vr_i, input wire [2:0] vr_i,
    input wire [23:0] alloc_size_i, input wire alloc_scan_i,
    input wire [39:0] data_i, input wire check_type_i, input wire [39:0] expected_type_i,
    input wire svc_valid_i, output wire svc_ready_o, input wire [3:0] svc_op_i,
    input wire [39:0] svc_ref_i, input wire [39:0] svc_class_i,
    input wire [23:0] svc_base_i, input wire [23:0] svc_size_i,
    input wire [39:0] svc_repr_i, input wire [2:0] svc_flags_i,
    input wire [5:0] svc_code_i,
    output wire rsp_valid_o, input wire rsp_ready_i,
    output reg [3:0] rsp_status_o, output reg [39:0] rsp_data_o,
    output wire mem_valid_o, input wire mem_ready_i,
    output wire mem_write_o, output wire [23:0] mem_addr_o, output wire [39:0] mem_data_o,
    input wire mem_rsp_valid_i, output wire mem_rsp_ready_o,
    input wire [39:0] mem_rsp_data_i, input wire mem_rsp_error_i,
    output wire store_valid_o, input wire store_ready_i, output wire [3:0] store_op_o,
    output wire [39:0] store_ref_o, output wire [39:0] store_class_o,
    output wire [23:0] store_size_o, output wire store_cond_o,
    output wire [23:0] store_offset_o, output wire [39:0] store_data_o,
    input wire store_rsp_valid_i, output wire store_rsp_ready_o,
    input wire [3:0] store_rsp_status_i,
    input wire [39:0] store_rsp_ref_i, input wire [39:0] store_rsp_class_i,
    input wire [23:0] store_rsp_size_i, input wire store_rsp_cond_i, input wire [39:0] store_rsp_data_i,
    output wire [37:0] dbg_next_identity_o, output wire [24:0] dbg_body_cursor_o,
    output wire [24:0] dbg_memory_words_o,
    output wire dbg_maintenance_o, input wire [1:0] dbg_class_code_i,
    output wire dbg_class_valid_o, output wire [39:0] dbg_compact_class_o,
    input wire [2:0] dbg_vr_i, output wire [39:0] dbg_vr_o,
    output wire [39:0] dbg_idx_o, output wire [39:0] dbg_reg_o,
    output wire dbg_selected_o, output wire [39:0] dbg_ref_o,
    output wire [39:0] dbg_class_o, output wire [23:0] dbg_size_o,
    output wire [23:0] dbg_base_o, output wire [39:0] dbg_repr_o, output wire [2:0] dbg_flags_o,
    input wire [3:0] dbg_slot_i, output wire dbg_valid_o,
    output wire [39:0] dbg_entry_ref_o, output wire [39:0] dbg_entry_class_o,
    output wire [23:0] dbg_entry_size_o, output wire [23:0] dbg_entry_base_o,
    output wire [39:0] dbg_entry_repr_o, output wire [2:0] dbg_entry_flags_o ,
    input wire cpu_gc_enable_i, input wire [15:0] cpu_gc_entry_i,
    output wire cpu_gc_active_o, output wire [3:0] cpu_last_status_o,
    input wire cpu_enable_i, input wire cpu_command_enable_i, input wire cpu_response_enable_i,
    input wire  cpu_boot_valid_i,
    output wire  cpu_boot_ready_o,
    input wire [1:0] cpu_boot_space_i,
    input wire [15:0] cpu_boot_addr_i,
    input wire [2:0] cpu_boot_lane_i,
    input wire [31:0] cpu_boot_data_i,
    input wire  cpu_start_i,
    input wire [15:0] cpu_entry_i,
    input wire  cpu_resume_i,
    input wire  cpu_irq_i,
    output wire  cpu_halted_o,
    output wire  cpu_service_o,
    output wire [3:0] cpu_service_code_o,
    output wire [3:0] cpu_fault_o,
    output wire  cpu_retire_o,
    output wire  cpu_cmd_valid_o,
    output wire [3:0] cpu_pager_o,
    output wire [3:0] cpu_index_o,
    output wire [2:0] cpu_register_o,
    output wire [1:0] cpu_memory_o,
    output wire [3:0] cpu_read_o,
    output wire  cpu_load_vr_o,
    output wire [2:0] cpu_vr_o,
    output wire [23:0] cpu_alloc_size_o,
    output wire  cpu_alloc_scan_o,
    output wire [39:0] cpu_data_o,
    output wire  cpu_check_type_o,
    output wire [39:0] cpu_expected_type_o,
    output wire  cpu_rsp_ready_o,
    output wire [15:0] cpu_pc_o,
    output wire [15:0] cpu_upcor_o,
    output wire [15:0] cpu_mark_o,
    output wire [23:0] cpu_sp_o,
    output wire [23:0] cpu_esp_o,
    output wire [23:0] cpu_csp_o,
    output wire [23:0] cpu_ap_o,
    output wire [23:0] cpu_apc_o,
    output wire [39:0] cpu_estkr_o,
    output wire [23:0] cpu_cstkr_o,
    output wire [39:0] cpu_symbol_o,
    output wire [39:0] cpu_object_o,
    output wire io_valid_o, input wire io_ready_i,
    output wire io_write_o, output wire [31:0] io_address_o, output wire [31:0] io_data_o,
    input wire io_response_i, output wire io_response_ready_o,
    input wire io_error_i, input wire [31:0] io_result_i,
    output wire [31:0] cpu_device_result_o,
    output wire [39:0] cpu_dbg_root_o,
    output wire [31:0] cpu_q_o,
    output wire [63:0] cpu_product_o,
    output wire [4:0] cpu_flags_o,
    output wire [4:0] cpu_fp_flags_o,
    output wire  cpu_lastcc_o,
    output wire [15:0] cpu_ucar_o,
    output wire [29:0] cpu_namarg_o,
    input wire [15:0] cpu_dbg_addr_i,
    output wire [31:0] cpu_dbg_rf_o,
    output wire [39:0] cpu_dbg_estk_o,
    output wire [23:0] cpu_dbg_cstk_o,
    output wire cpu_dbg_code_valid_o, output wire [39:0] cpu_dbg_code_data_o, output wire [39:0] cpu_dbg_code_type_o
);

wire gc_valid, gc_ready, gc_response, gc_response_ready, gc_committed, gc_explicit;
wire [3:0] gc_operation, gc_status;
wire [39:0] gc_data, gc_root, gc_result;
logik #(.CODE_WORDS(8192)) processor(
    .io_valid_o(io_valid_o), .io_ready_i(io_ready_i), .io_write_o(io_write_o),
    .io_address_o(io_address_o), .io_data_o(io_data_o), .io_response_i(io_response_i),
    .io_response_ready_o(io_response_ready_o), .io_error_i(io_error_i), .io_result_i(io_result_i),
    .device_result_o(cpu_device_result_o), .dbg_root_o(cpu_dbg_root_o),
    .gc_enable_i(cpu_gc_enable_i),.gc_entry_i(cpu_gc_entry_i),.gc_active_o(cpu_gc_active_o),.gc_explicit_o(gc_explicit),
    .gc_valid_o(gc_valid),.gc_ready_i(gc_ready),.gc_operation_o(gc_operation),.gc_data_o(gc_data),.gc_root_o(gc_root),
    .gc_response_i(gc_response),.gc_response_ready_o(gc_response_ready),.gc_status_i(gc_status),
    .gc_result_i(gc_result),.gc_committed_i(gc_committed),.last_status_o(cpu_last_status_o),
    .clk_i(clk_i),
    .rst_i(rst_i),
    .boot_valid_i(cpu_boot_valid_i),
    .boot_ready_o(cpu_boot_ready_o),
    .boot_space_i(cpu_boot_space_i),
    .boot_addr_i(cpu_boot_addr_i),
    .boot_lane_i(cpu_boot_lane_i),
    .boot_data_i(cpu_boot_data_i),
    .start_i(cpu_start_i),
    .entry_i(cpu_entry_i),
    .resume_i(cpu_resume_i),
    .irq_i(cpu_irq_i),
    .halted_o(cpu_halted_o),
    .service_o(cpu_service_o),
    .service_code_o(cpu_service_code_o),
    .fault_o(cpu_fault_o),
    .retire_o(cpu_retire_o),
    .cmd_valid_o(cpu_cmd_valid_o),
    .cmd_ready_i((cmd_ready_o && cpu_enable_i && cpu_command_enable_i)),
    .pager_o(cpu_pager_o),
    .index_o(cpu_index_o),
    .register_o(cpu_register_o),
    .memory_o(cpu_memory_o),
    .read_o(cpu_read_o),
    .load_vr_o(cpu_load_vr_o),
    .vr_o(cpu_vr_o),
    .alloc_size_o(cpu_alloc_size_o),
    .alloc_scan_o(cpu_alloc_scan_o),
    .data_o(cpu_data_o),
    .check_type_o(cpu_check_type_o),
    .expected_type_o(cpu_expected_type_o),
    .rsp_valid_i((rsp_valid_o && cpu_enable_i && cpu_response_enable_i)),
    .rsp_ready_o(cpu_rsp_ready_o),
    .rsp_status_i(rsp_status_o),
    .rsp_data_i(rsp_data_o),
    .pc_o(cpu_pc_o),
    .upcor_o(cpu_upcor_o),
    .mark_o(cpu_mark_o),
    .sp_o(cpu_sp_o),
    .esp_o(cpu_esp_o),
    .csp_o(cpu_csp_o),
    .ap_o(cpu_ap_o),
    .apc_o(cpu_apc_o),
    .estkr_o(cpu_estkr_o),
    .cstkr_o(cpu_cstkr_o),
    .symbol_o(cpu_symbol_o),
    .object_o(cpu_object_o),
    .q_o(cpu_q_o),
    .product_o(cpu_product_o),
    .flags_o(cpu_flags_o),
    .fp_flags_o(cpu_fp_flags_o),
    .lastcc_o(cpu_lastcc_o),
    .ucar_o(cpu_ucar_o),
    .namarg_o(cpu_namarg_o),
    .dbg_addr_i(cpu_dbg_addr_i),
    .dbg_rf_o(cpu_dbg_rf_o),
    .dbg_estk_o(cpu_dbg_estk_o),
    .dbg_cstk_o(cpu_dbg_cstk_o),
    .dbg_code_valid_o(cpu_dbg_code_valid_o),.dbg_code_data_o(cpu_dbg_code_data_o),.dbg_code_type_o(cpu_dbg_code_type_o)
);
assign dbg_memory_words_o = 25'(`REKURSIV_SIM_MEMORY_WORDS);
objekt #(.PAGER_BITS(4), .MEMORY_WORDS(`REKURSIV_SIM_MEMORY_WORDS)) core(
    .gc_enable_i(cpu_gc_enable_i),.gc_active_i(cpu_gc_active_o),.gc_explicit_i(gc_explicit),
    .gc_valid_i(gc_valid),.gc_ready_o(gc_ready),.gc_operation_i(gc_operation),.gc_data_i(gc_data),.gc_root_i(gc_root),
    .gc_response_o(gc_response),.gc_response_ready_i(gc_response_ready),.gc_status_o(gc_status),
    .gc_result_o(gc_result),.gc_committed_o(gc_committed),
    .pager_i(cpu_enable_i ? cpu_pager_o : pager_i),
    .index_i(cpu_enable_i ? cpu_index_o : index_i),
    .register_i(cpu_enable_i ? cpu_register_o : register_i),
    .memory_i(cpu_enable_i ? cpu_memory_o : memory_i),
    .read_i(cpu_enable_i ? cpu_read_o : read_i),
    .load_vr_i(cpu_enable_i ? cpu_load_vr_o : load_vr_i),
    .vr_i(cpu_enable_i ? cpu_vr_o : vr_i),
    .alloc_size_i(cpu_enable_i ? cpu_alloc_size_o : alloc_size_i),
    .alloc_scan_i(cpu_enable_i ? cpu_alloc_scan_o : alloc_scan_i),
    .data_i(cpu_enable_i ? cpu_data_o : data_i),
    .check_type_i(cpu_enable_i ? cpu_check_type_o : check_type_i),
    .expected_type_i(cpu_enable_i ? cpu_expected_type_o : expected_type_i),
    .cmd_valid_i(cpu_enable_i ? (cpu_cmd_valid_o && cpu_command_enable_i) : cmd_valid_i),
    .rsp_ready_i(cpu_enable_i ? (cpu_rsp_ready_o && cpu_response_enable_i) : rsp_ready_i),
    .run_i(cpu_enable_i ? 1'b1 : run_i),
    .*
);
endmodule
