[package]
name = "rekursiv-emulator"
version.workspace = true
edition.workspace = true

[features]
default = ["window"]
window = ["dep:minifb", "dep:raw-window-handle", "dep:x11-dl"]

[dependencies]
rekursiv-asm = { path = "../rekursiv-asm" }
rekursiv-model = { path = "../rekursiv-model" }
rekursiv-devices = { path = "../rekursiv-devices" }
rekursiv-smalltalk = { path = "../rekursiv-smalltalk" }
eyre = "0.6"
minifb = { version = "0.28", optional = true }

[target.'cfg(target_os = "linux")'.dependencies]
raw-window-handle = { version = "0.6", optional = true }
x11-dl = { version = "2.21", optional = true }

[dev-dependencies]
rekursiv-sim = { path = "../rekursiv-sim" }
